import 'dart:async';
import 'dart:typed_data';
import 'package:another_flushbar/flushbar.dart';
import 'dart:ui' as ui;
import 'package:create_signature/shared/shared.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:ui';
import 'package:signature/signature.dart';
part 'views/splashScreen.dart';
part 'views/drawPad.dart';
part 'views/home_page.dart';
